version: '2'
services:
    dumb-app:
        image: dumb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dumb-postgresql:5432/dumb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dumb-postgresql:
        extends:
            file: postgresql.yml
            service: dumb-postgresql
